# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f9a95d3297ef1aa54a444a6b3bb7f58b2c282c2b5edd84887eb559d5ff5651daf831797ed2606ce07de4e904ec53da6dcac42d1032350cd7a13586168e7b3f72

test:
  secret_key_base: e443ee207916fb4e2ed9a6e1cab8c767bcc5e4737cf1dab9557e2c8c52fe15bbe106f54625dbc8d41d22b1b58616d1cea933eddc5145f66b93902bb4a50b96bb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
